### ISSUE TITLE
Atom cannot update from `language-inno 2.1.6` to `language-innosetup 2.2.0`

### ISSUE THREAD

**Issue by jpluimers** [idleberg/atom-language-innosetup#1]
Atom cannot update from `language-inno 2.1.6` to `language-innosetup 2.2.0`.

When you try, you will see this progress bar forever both on Mac and Windows editions of Atom (both are at 1.9.6):

![Downloads the update forever](https://www.dropbox.com/s/m46d03c81p6heax/Screenshot%202016-08-08%2014.09.46.png?raw=1)
https://www.dropbox.com/s/m46d03c81p6heax/Screenshot%202016-08-08%2014.09.46.png?dl=0

**Comment by idleberg** [comment]
See [this issue](https://github.com/atom/settings-view/issues/532)

**Comment by jpluimers** [comment]
What's the recommended action? Uninstall `language-inno` and install `language-innosetup`?

**Comment by idleberg** [comment]
As far as I remember, `language-innosetup` gets installed fine, but the folder of the old version doesn't get removed (not sure if this is a known issue). The hanging update happens with _every_ update, it has nothing to do with this particular name-change. I usually reload the window when the update dialog hangs.

**Comment by jpluimers** [comment]
Thanks: that's indeed the case and `language-innosetup` correctly updated to version `2.2.1` (see screenshot). 

Where should I remove the old folder?

![both language-inno and language-innosetup installed](https://www.dropbox.com/s/5bzv5yg7frz992b/Screenshot%202016-08-09%2004.25.08.png?raw=1)

**Comment by idleberg** [comment]
You can either delete the old folder from your package folder or uninstall it within Atom. I've posted an [issue](https://github.com/atom/apm/issues/600) for this in the apm repository, please subscribe there for updates on the issue.
