### ISSUE TITLE
All lines after [Code] section lose syntax highlighting

### ISSUE THREAD

**Issue by shluzen** [idleberg/atom-language-innosetup#5]
First of all, thank you very much for this excellent implementation of language support for inno setup!

I've found one bug that affects many of my scripts. All lines after a [Code] block (including the lines within [Code]) lose their syntax highlighting.

I'm using Atom 1.18.0 x64 (Win10), with One Dark (UI/syntax).

The issue follows the [Code] section wherever it is located (top, bottom, etc...)

**Comment by idleberg** [comment]
The new version should improve the situation, but it's not perfect either. Thanks for reporting.

**Comment by shluzen** [comment]
2.12.0 completely corrects the issue in all of my .iss files - thanks a bunch  for the extremely quick turnaround!
